# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cong/CS-Y2398/UAV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cong/CS-Y2398/UAV/pathPlanningAlgorithm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cong/CS-Y2398/UAV/pathPlanningAlgorithm/CMakeFiles /home/cong/CS-Y2398/UAV/pathPlanningAlgorithm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cong/CS-Y2398/UAV/pathPlanningAlgorithm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uav

# Build rule for target.
uav: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uav
.PHONY : uav

# fast build rule for target.
uav/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/build
.PHONY : uav/fast

BattleRegionSegment/RegionSegement.o: BattleRegionSegment/RegionSegement.cpp.o
.PHONY : BattleRegionSegment/RegionSegement.o

# target to build an object file
BattleRegionSegment/RegionSegement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/BattleRegionSegment/RegionSegement.cpp.o
.PHONY : BattleRegionSegment/RegionSegement.cpp.o

BattleRegionSegment/RegionSegement.i: BattleRegionSegment/RegionSegement.cpp.i
.PHONY : BattleRegionSegment/RegionSegement.i

# target to preprocess a source file
BattleRegionSegment/RegionSegement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/BattleRegionSegment/RegionSegement.cpp.i
.PHONY : BattleRegionSegment/RegionSegement.cpp.i

BattleRegionSegment/RegionSegement.s: BattleRegionSegment/RegionSegement.cpp.s
.PHONY : BattleRegionSegment/RegionSegement.s

# target to generate assembly for a file
BattleRegionSegment/RegionSegement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/BattleRegionSegment/RegionSegement.cpp.s
.PHONY : BattleRegionSegment/RegionSegement.cpp.s

BindDataSotrage.o: BindDataSotrage.cpp.o
.PHONY : BindDataSotrage.o

# target to build an object file
BindDataSotrage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/BindDataSotrage.cpp.o
.PHONY : BindDataSotrage.cpp.o

BindDataSotrage.i: BindDataSotrage.cpp.i
.PHONY : BindDataSotrage.i

# target to preprocess a source file
BindDataSotrage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/BindDataSotrage.cpp.i
.PHONY : BindDataSotrage.cpp.i

BindDataSotrage.s: BindDataSotrage.cpp.s
.PHONY : BindDataSotrage.s

# target to generate assembly for a file
BindDataSotrage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/BindDataSotrage.cpp.s
.PHONY : BindDataSotrage.cpp.s

DroneManager.o: DroneManager.cpp.o
.PHONY : DroneManager.o

# target to build an object file
DroneManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/DroneManager.cpp.o
.PHONY : DroneManager.cpp.o

DroneManager.i: DroneManager.cpp.i
.PHONY : DroneManager.i

# target to preprocess a source file
DroneManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/DroneManager.cpp.i
.PHONY : DroneManager.cpp.i

DroneManager.s: DroneManager.cpp.s
.PHONY : DroneManager.s

# target to generate assembly for a file
DroneManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/DroneManager.cpp.s
.PHONY : DroneManager.cpp.s

FusionAndAttack/complex/TargetFusionAttack.o: FusionAndAttack/complex/TargetFusionAttack.cpp.o
.PHONY : FusionAndAttack/complex/TargetFusionAttack.o

# target to build an object file
FusionAndAttack/complex/TargetFusionAttack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/FusionAndAttack/complex/TargetFusionAttack.cpp.o
.PHONY : FusionAndAttack/complex/TargetFusionAttack.cpp.o

FusionAndAttack/complex/TargetFusionAttack.i: FusionAndAttack/complex/TargetFusionAttack.cpp.i
.PHONY : FusionAndAttack/complex/TargetFusionAttack.i

# target to preprocess a source file
FusionAndAttack/complex/TargetFusionAttack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/FusionAndAttack/complex/TargetFusionAttack.cpp.i
.PHONY : FusionAndAttack/complex/TargetFusionAttack.cpp.i

FusionAndAttack/complex/TargetFusionAttack.s: FusionAndAttack/complex/TargetFusionAttack.cpp.s
.PHONY : FusionAndAttack/complex/TargetFusionAttack.s

# target to generate assembly for a file
FusionAndAttack/complex/TargetFusionAttack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/FusionAndAttack/complex/TargetFusionAttack.cpp.s
.PHONY : FusionAndAttack/complex/TargetFusionAttack.cpp.s

InitData.o: InitData.cpp.o
.PHONY : InitData.o

# target to build an object file
InitData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/InitData.cpp.o
.PHONY : InitData.cpp.o

InitData.i: InitData.cpp.i
.PHONY : InitData.i

# target to preprocess a source file
InitData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/InitData.cpp.i
.PHONY : InitData.cpp.i

InitData.s: InitData.cpp.s
.PHONY : InitData.s

# target to generate assembly for a file
InitData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/InitData.cpp.s
.PHONY : InitData.cpp.s

MultiDroneInformationManager/DB/MessageManager-odb.o: MultiDroneInformationManager/DB/MessageManager-odb.cxx.o
.PHONY : MultiDroneInformationManager/DB/MessageManager-odb.o

# target to build an object file
MultiDroneInformationManager/DB/MessageManager-odb.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DB/MessageManager-odb.cxx.o
.PHONY : MultiDroneInformationManager/DB/MessageManager-odb.cxx.o

MultiDroneInformationManager/DB/MessageManager-odb.i: MultiDroneInformationManager/DB/MessageManager-odb.cxx.i
.PHONY : MultiDroneInformationManager/DB/MessageManager-odb.i

# target to preprocess a source file
MultiDroneInformationManager/DB/MessageManager-odb.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DB/MessageManager-odb.cxx.i
.PHONY : MultiDroneInformationManager/DB/MessageManager-odb.cxx.i

MultiDroneInformationManager/DB/MessageManager-odb.s: MultiDroneInformationManager/DB/MessageManager-odb.cxx.s
.PHONY : MultiDroneInformationManager/DB/MessageManager-odb.s

# target to generate assembly for a file
MultiDroneInformationManager/DB/MessageManager-odb.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DB/MessageManager-odb.cxx.s
.PHONY : MultiDroneInformationManager/DB/MessageManager-odb.cxx.s

MultiDroneInformationManager/DB/MessageManager.o: MultiDroneInformationManager/DB/MessageManager.cpp.o
.PHONY : MultiDroneInformationManager/DB/MessageManager.o

# target to build an object file
MultiDroneInformationManager/DB/MessageManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DB/MessageManager.cpp.o
.PHONY : MultiDroneInformationManager/DB/MessageManager.cpp.o

MultiDroneInformationManager/DB/MessageManager.i: MultiDroneInformationManager/DB/MessageManager.cpp.i
.PHONY : MultiDroneInformationManager/DB/MessageManager.i

# target to preprocess a source file
MultiDroneInformationManager/DB/MessageManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DB/MessageManager.cpp.i
.PHONY : MultiDroneInformationManager/DB/MessageManager.cpp.i

MultiDroneInformationManager/DB/MessageManager.s: MultiDroneInformationManager/DB/MessageManager.cpp.s
.PHONY : MultiDroneInformationManager/DB/MessageManager.s

# target to generate assembly for a file
MultiDroneInformationManager/DB/MessageManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DB/MessageManager.cpp.s
.PHONY : MultiDroneInformationManager/DB/MessageManager.cpp.s

MultiDroneInformationManager/DataBase.o: MultiDroneInformationManager/DataBase.cpp.o
.PHONY : MultiDroneInformationManager/DataBase.o

# target to build an object file
MultiDroneInformationManager/DataBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DataBase.cpp.o
.PHONY : MultiDroneInformationManager/DataBase.cpp.o

MultiDroneInformationManager/DataBase.i: MultiDroneInformationManager/DataBase.cpp.i
.PHONY : MultiDroneInformationManager/DataBase.i

# target to preprocess a source file
MultiDroneInformationManager/DataBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DataBase.cpp.i
.PHONY : MultiDroneInformationManager/DataBase.cpp.i

MultiDroneInformationManager/DataBase.s: MultiDroneInformationManager/DataBase.cpp.s
.PHONY : MultiDroneInformationManager/DataBase.s

# target to generate assembly for a file
MultiDroneInformationManager/DataBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DataBase.cpp.s
.PHONY : MultiDroneInformationManager/DataBase.cpp.s

MultiDroneInformationManager/DroneInformationManager.o: MultiDroneInformationManager/DroneInformationManager.cpp.o
.PHONY : MultiDroneInformationManager/DroneInformationManager.o

# target to build an object file
MultiDroneInformationManager/DroneInformationManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DroneInformationManager.cpp.o
.PHONY : MultiDroneInformationManager/DroneInformationManager.cpp.o

MultiDroneInformationManager/DroneInformationManager.i: MultiDroneInformationManager/DroneInformationManager.cpp.i
.PHONY : MultiDroneInformationManager/DroneInformationManager.i

# target to preprocess a source file
MultiDroneInformationManager/DroneInformationManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DroneInformationManager.cpp.i
.PHONY : MultiDroneInformationManager/DroneInformationManager.cpp.i

MultiDroneInformationManager/DroneInformationManager.s: MultiDroneInformationManager/DroneInformationManager.cpp.s
.PHONY : MultiDroneInformationManager/DroneInformationManager.s

# target to generate assembly for a file
MultiDroneInformationManager/DroneInformationManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/DroneInformationManager.cpp.s
.PHONY : MultiDroneInformationManager/DroneInformationManager.cpp.s

MultiDroneInformationManager/LeaderSelect.o: MultiDroneInformationManager/LeaderSelect.cpp.o
.PHONY : MultiDroneInformationManager/LeaderSelect.o

# target to build an object file
MultiDroneInformationManager/LeaderSelect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/LeaderSelect.cpp.o
.PHONY : MultiDroneInformationManager/LeaderSelect.cpp.o

MultiDroneInformationManager/LeaderSelect.i: MultiDroneInformationManager/LeaderSelect.cpp.i
.PHONY : MultiDroneInformationManager/LeaderSelect.i

# target to preprocess a source file
MultiDroneInformationManager/LeaderSelect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/LeaderSelect.cpp.i
.PHONY : MultiDroneInformationManager/LeaderSelect.cpp.i

MultiDroneInformationManager/LeaderSelect.s: MultiDroneInformationManager/LeaderSelect.cpp.s
.PHONY : MultiDroneInformationManager/LeaderSelect.s

# target to generate assembly for a file
MultiDroneInformationManager/LeaderSelect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/LeaderSelect.cpp.s
.PHONY : MultiDroneInformationManager/LeaderSelect.cpp.s

MultiDroneInformationManager/test_DroneInformation.o: MultiDroneInformationManager/test_DroneInformation.cpp.o
.PHONY : MultiDroneInformationManager/test_DroneInformation.o

# target to build an object file
MultiDroneInformationManager/test_DroneInformation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/test_DroneInformation.cpp.o
.PHONY : MultiDroneInformationManager/test_DroneInformation.cpp.o

MultiDroneInformationManager/test_DroneInformation.i: MultiDroneInformationManager/test_DroneInformation.cpp.i
.PHONY : MultiDroneInformationManager/test_DroneInformation.i

# target to preprocess a source file
MultiDroneInformationManager/test_DroneInformation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/test_DroneInformation.cpp.i
.PHONY : MultiDroneInformationManager/test_DroneInformation.cpp.i

MultiDroneInformationManager/test_DroneInformation.s: MultiDroneInformationManager/test_DroneInformation.cpp.s
.PHONY : MultiDroneInformationManager/test_DroneInformation.s

# target to generate assembly for a file
MultiDroneInformationManager/test_DroneInformation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/MultiDroneInformationManager/test_DroneInformation.cpp.s
.PHONY : MultiDroneInformationManager/test_DroneInformation.cpp.s

Remote/protocol/remote_protocol.o: Remote/protocol/remote_protocol.cpp.o
.PHONY : Remote/protocol/remote_protocol.o

# target to build an object file
Remote/protocol/remote_protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/protocol/remote_protocol.cpp.o
.PHONY : Remote/protocol/remote_protocol.cpp.o

Remote/protocol/remote_protocol.i: Remote/protocol/remote_protocol.cpp.i
.PHONY : Remote/protocol/remote_protocol.i

# target to preprocess a source file
Remote/protocol/remote_protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/protocol/remote_protocol.cpp.i
.PHONY : Remote/protocol/remote_protocol.cpp.i

Remote/protocol/remote_protocol.s: Remote/protocol/remote_protocol.cpp.s
.PHONY : Remote/protocol/remote_protocol.s

# target to generate assembly for a file
Remote/protocol/remote_protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/protocol/remote_protocol.cpp.s
.PHONY : Remote/protocol/remote_protocol.cpp.s

Remote/socket/remote_messages.o: Remote/socket/remote_messages.cpp.o
.PHONY : Remote/socket/remote_messages.o

# target to build an object file
Remote/socket/remote_messages.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/socket/remote_messages.cpp.o
.PHONY : Remote/socket/remote_messages.cpp.o

Remote/socket/remote_messages.i: Remote/socket/remote_messages.cpp.i
.PHONY : Remote/socket/remote_messages.i

# target to preprocess a source file
Remote/socket/remote_messages.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/socket/remote_messages.cpp.i
.PHONY : Remote/socket/remote_messages.cpp.i

Remote/socket/remote_messages.s: Remote/socket/remote_messages.cpp.s
.PHONY : Remote/socket/remote_messages.s

# target to generate assembly for a file
Remote/socket/remote_messages.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/socket/remote_messages.cpp.s
.PHONY : Remote/socket/remote_messages.cpp.s

Remote/socket/remote_msgSendRecv.o: Remote/socket/remote_msgSendRecv.cpp.o
.PHONY : Remote/socket/remote_msgSendRecv.o

# target to build an object file
Remote/socket/remote_msgSendRecv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/socket/remote_msgSendRecv.cpp.o
.PHONY : Remote/socket/remote_msgSendRecv.cpp.o

Remote/socket/remote_msgSendRecv.i: Remote/socket/remote_msgSendRecv.cpp.i
.PHONY : Remote/socket/remote_msgSendRecv.i

# target to preprocess a source file
Remote/socket/remote_msgSendRecv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/socket/remote_msgSendRecv.cpp.i
.PHONY : Remote/socket/remote_msgSendRecv.cpp.i

Remote/socket/remote_msgSendRecv.s: Remote/socket/remote_msgSendRecv.cpp.s
.PHONY : Remote/socket/remote_msgSendRecv.s

# target to generate assembly for a file
Remote/socket/remote_msgSendRecv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/socket/remote_msgSendRecv.cpp.s
.PHONY : Remote/socket/remote_msgSendRecv.cpp.s

Remote/socket/remote_socket.o: Remote/socket/remote_socket.cpp.o
.PHONY : Remote/socket/remote_socket.o

# target to build an object file
Remote/socket/remote_socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/socket/remote_socket.cpp.o
.PHONY : Remote/socket/remote_socket.cpp.o

Remote/socket/remote_socket.i: Remote/socket/remote_socket.cpp.i
.PHONY : Remote/socket/remote_socket.i

# target to preprocess a source file
Remote/socket/remote_socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/socket/remote_socket.cpp.i
.PHONY : Remote/socket/remote_socket.cpp.i

Remote/socket/remote_socket.s: Remote/socket/remote_socket.cpp.s
.PHONY : Remote/socket/remote_socket.s

# target to generate assembly for a file
Remote/socket/remote_socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/Remote/socket/remote_socket.cpp.s
.PHONY : Remote/socket/remote_socket.cpp.s

flightControl.o: flightControl.cpp.o
.PHONY : flightControl.o

# target to build an object file
flightControl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/flightControl.cpp.o
.PHONY : flightControl.cpp.o

flightControl.i: flightControl.cpp.i
.PHONY : flightControl.i

# target to preprocess a source file
flightControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/flightControl.cpp.i
.PHONY : flightControl.cpp.i

flightControl.s: flightControl.cpp.s
.PHONY : flightControl.s

# target to generate assembly for a file
flightControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/flightControl.cpp.s
.PHONY : flightControl.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/main.cpp.s
.PHONY : main.cpp.s

pathPlanning.o: pathPlanning.cpp.o
.PHONY : pathPlanning.o

# target to build an object file
pathPlanning.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/pathPlanning.cpp.o
.PHONY : pathPlanning.cpp.o

pathPlanning.i: pathPlanning.cpp.i
.PHONY : pathPlanning.i

# target to preprocess a source file
pathPlanning.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/pathPlanning.cpp.i
.PHONY : pathPlanning.cpp.i

pathPlanning.s: pathPlanning.cpp.s
.PHONY : pathPlanning.s

# target to generate assembly for a file
pathPlanning.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/pathPlanning.cpp.s
.PHONY : pathPlanning.cpp.s

returnHome.o: returnHome.cpp.o
.PHONY : returnHome.o

# target to build an object file
returnHome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/returnHome.cpp.o
.PHONY : returnHome.cpp.o

returnHome.i: returnHome.cpp.i
.PHONY : returnHome.i

# target to preprocess a source file
returnHome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/returnHome.cpp.i
.PHONY : returnHome.cpp.i

returnHome.s: returnHome.cpp.s
.PHONY : returnHome.s

# target to generate assembly for a file
returnHome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/returnHome.cpp.s
.PHONY : returnHome.cpp.s

statuscheck.o: statuscheck.cpp.o
.PHONY : statuscheck.o

# target to build an object file
statuscheck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/statuscheck.cpp.o
.PHONY : statuscheck.cpp.o

statuscheck.i: statuscheck.cpp.i
.PHONY : statuscheck.i

# target to preprocess a source file
statuscheck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/statuscheck.cpp.i
.PHONY : statuscheck.cpp.i

statuscheck.s: statuscheck.cpp.s
.PHONY : statuscheck.s

# target to generate assembly for a file
statuscheck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/statuscheck.cpp.s
.PHONY : statuscheck.cpp.s

timersend.o: timersend.cpp.o
.PHONY : timersend.o

# target to build an object file
timersend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/timersend.cpp.o
.PHONY : timersend.cpp.o

timersend.i: timersend.cpp.i
.PHONY : timersend.i

# target to preprocess a source file
timersend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/timersend.cpp.i
.PHONY : timersend.cpp.i

timersend.s: timersend.cpp.s
.PHONY : timersend.s

# target to generate assembly for a file
timersend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/timersend.cpp.s
.PHONY : timersend.cpp.s

timesync.o: timesync.cpp.o
.PHONY : timesync.o

# target to build an object file
timesync.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/timesync.cpp.o
.PHONY : timesync.cpp.o

timesync.i: timesync.cpp.i
.PHONY : timesync.i

# target to preprocess a source file
timesync.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/timesync.cpp.i
.PHONY : timesync.cpp.i

timesync.s: timesync.cpp.s
.PHONY : timesync.s

# target to generate assembly for a file
timesync.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/timesync.cpp.s
.PHONY : timesync.cpp.s

uavCommand.o: uavCommand.cpp.o
.PHONY : uavCommand.o

# target to build an object file
uavCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/uavCommand.cpp.o
.PHONY : uavCommand.cpp.o

uavCommand.i: uavCommand.cpp.i
.PHONY : uavCommand.i

# target to preprocess a source file
uavCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/uavCommand.cpp.i
.PHONY : uavCommand.cpp.i

uavCommand.s: uavCommand.cpp.s
.PHONY : uavCommand.s

# target to generate assembly for a file
uavCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/uavCommand.cpp.s
.PHONY : uavCommand.cpp.s

uavConfigure.o: uavConfigure.cpp.o
.PHONY : uavConfigure.o

# target to build an object file
uavConfigure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/uavConfigure.cpp.o
.PHONY : uavConfigure.cpp.o

uavConfigure.i: uavConfigure.cpp.i
.PHONY : uavConfigure.i

# target to preprocess a source file
uavConfigure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/uavConfigure.cpp.i
.PHONY : uavConfigure.cpp.i

uavConfigure.s: uavConfigure.cpp.s
.PHONY : uavConfigure.s

# target to generate assembly for a file
uavConfigure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/uavConfigure.cpp.s
.PHONY : uavConfigure.cpp.s

write_domain_control/read_domain_control.o: write_domain_control/read_domain_control.cpp.o
.PHONY : write_domain_control/read_domain_control.o

# target to build an object file
write_domain_control/read_domain_control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/write_domain_control/read_domain_control.cpp.o
.PHONY : write_domain_control/read_domain_control.cpp.o

write_domain_control/read_domain_control.i: write_domain_control/read_domain_control.cpp.i
.PHONY : write_domain_control/read_domain_control.i

# target to preprocess a source file
write_domain_control/read_domain_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/write_domain_control/read_domain_control.cpp.i
.PHONY : write_domain_control/read_domain_control.cpp.i

write_domain_control/read_domain_control.s: write_domain_control/read_domain_control.cpp.s
.PHONY : write_domain_control/read_domain_control.s

# target to generate assembly for a file
write_domain_control/read_domain_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav.dir/build.make CMakeFiles/uav.dir/write_domain_control/read_domain_control.cpp.s
.PHONY : write_domain_control/read_domain_control.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... uav"
	@echo "... BattleRegionSegment/RegionSegement.o"
	@echo "... BattleRegionSegment/RegionSegement.i"
	@echo "... BattleRegionSegment/RegionSegement.s"
	@echo "... BindDataSotrage.o"
	@echo "... BindDataSotrage.i"
	@echo "... BindDataSotrage.s"
	@echo "... DroneManager.o"
	@echo "... DroneManager.i"
	@echo "... DroneManager.s"
	@echo "... FusionAndAttack/complex/TargetFusionAttack.o"
	@echo "... FusionAndAttack/complex/TargetFusionAttack.i"
	@echo "... FusionAndAttack/complex/TargetFusionAttack.s"
	@echo "... InitData.o"
	@echo "... InitData.i"
	@echo "... InitData.s"
	@echo "... MultiDroneInformationManager/DB/MessageManager-odb.o"
	@echo "... MultiDroneInformationManager/DB/MessageManager-odb.i"
	@echo "... MultiDroneInformationManager/DB/MessageManager-odb.s"
	@echo "... MultiDroneInformationManager/DB/MessageManager.o"
	@echo "... MultiDroneInformationManager/DB/MessageManager.i"
	@echo "... MultiDroneInformationManager/DB/MessageManager.s"
	@echo "... MultiDroneInformationManager/DataBase.o"
	@echo "... MultiDroneInformationManager/DataBase.i"
	@echo "... MultiDroneInformationManager/DataBase.s"
	@echo "... MultiDroneInformationManager/DroneInformationManager.o"
	@echo "... MultiDroneInformationManager/DroneInformationManager.i"
	@echo "... MultiDroneInformationManager/DroneInformationManager.s"
	@echo "... MultiDroneInformationManager/LeaderSelect.o"
	@echo "... MultiDroneInformationManager/LeaderSelect.i"
	@echo "... MultiDroneInformationManager/LeaderSelect.s"
	@echo "... MultiDroneInformationManager/test_DroneInformation.o"
	@echo "... MultiDroneInformationManager/test_DroneInformation.i"
	@echo "... MultiDroneInformationManager/test_DroneInformation.s"
	@echo "... Remote/protocol/remote_protocol.o"
	@echo "... Remote/protocol/remote_protocol.i"
	@echo "... Remote/protocol/remote_protocol.s"
	@echo "... Remote/socket/remote_messages.o"
	@echo "... Remote/socket/remote_messages.i"
	@echo "... Remote/socket/remote_messages.s"
	@echo "... Remote/socket/remote_msgSendRecv.o"
	@echo "... Remote/socket/remote_msgSendRecv.i"
	@echo "... Remote/socket/remote_msgSendRecv.s"
	@echo "... Remote/socket/remote_socket.o"
	@echo "... Remote/socket/remote_socket.i"
	@echo "... Remote/socket/remote_socket.s"
	@echo "... flightControl.o"
	@echo "... flightControl.i"
	@echo "... flightControl.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pathPlanning.o"
	@echo "... pathPlanning.i"
	@echo "... pathPlanning.s"
	@echo "... returnHome.o"
	@echo "... returnHome.i"
	@echo "... returnHome.s"
	@echo "... statuscheck.o"
	@echo "... statuscheck.i"
	@echo "... statuscheck.s"
	@echo "... timersend.o"
	@echo "... timersend.i"
	@echo "... timersend.s"
	@echo "... timesync.o"
	@echo "... timesync.i"
	@echo "... timesync.s"
	@echo "... uavCommand.o"
	@echo "... uavCommand.i"
	@echo "... uavCommand.s"
	@echo "... uavConfigure.o"
	@echo "... uavConfigure.i"
	@echo "... uavConfigure.s"
	@echo "... write_domain_control/read_domain_control.o"
	@echo "... write_domain_control/read_domain_control.i"
	@echo "... write_domain_control/read_domain_control.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

